### ISSUE TITLE
Testing imaging barcodes on pins

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#10]
Test whether can see barcode on pin in dorsal view with different specimen sizes and shapes and if it can be automatically read.

This is because the imaging is separate to beeping it into the app. Images need to be united with other data - this will be done via barcode (read automatically in image).

Maybe image dorsally every one of out test ones (then we have a large sample). We can then try and automatically read the barcodes of all of them by running a script and looking at success rates.

Would need to use tweesers to put so visible in dorsal view.

Estimate = 1 days work for adding barcodes and imaging.

Then need to run script and try and read barcode automatically.

**Comment by chelseagraham** [comment]
Testing to determine if barcode label with data matrix (size 1.2 cm x 0.5 cm) can be captured by Dorsal Canon in a quality that is machine readable by taking images of the barcode label oriented at 90 degrees from other labels on the pin. 

This will not be possible for specimens over a certain size with the Canon for certain. It might be possible for the Raspberry Pi cameras.

Roberta mentions that having a legible barcode in an image might not be necessary if the unique identifier for the set of images can be sent to the app to be connected to the barcode.

**Comment by chelseagraham** [comment]
121 images of insects from the DaSSCo test collection with the following FOV breakdown were taken on 6 and 7 March 2023:
#1: 1x FOV (3.6 cm x 2.4 cm) **48** (19/48 appear out of focus or obscured)
#2: 4x FOV (14.4 cm x 9.6 cm) **24** (3/24 appear out of focus or obscured)
#3: 8.3x FOV / A4 / highest setting on camera stand (30.0 cm x 19.9 cm) **4** (4/4 appear out of focus or obscured)
#4: 1.5x FOV (5.4 cm x 3.6 cm) **45** (24/45 appear out of focus or obscured)

Barcode labels were extended perpendicular to the catalog labels, sometimes in different iterations to test effectiveness. As a rule, the barcode labels were not easily visible for larger specimens and were out of focus for multi-specimen pins or pins with many catalog labels due to depth of field. The majority of specimens in the DaSSCo test collections are small, single specimen pins, thus the concentration of images in groups 1 and 4. 

By eye, 50 out of 121 the sample appear to be out of focus or obscured by the insect. 

All of the images should be inspected to see if the barcode can be read digitally.

The images are located at 
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Pinned Insects Working Data/BarcodeVisibility_DorsalCanon

**Comment by chelseagraham** [comment]
From Thomas:

[barcodes_pinned_insects.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/11063570/barcodes_pinned_insects.pdf)

Barcodes only detected in 18/121 images

**Comment by chelseagraham** [comment]
29 March Bi-weekly meeting:


[DetectionofDataMatrices.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/11077203/DetectionofDataMatrices.pdf)

**Comment by chelseagraham** [comment]
Hi @jlegind is this a closed ticket?

**Comment by jlegind** [comment]
@chelseagraham This ticket is not closed and I see the issues on the images above.
The image where the QR code is blurred is probably unsalvageable. Those with partially obscured QRs might be readable if QR error correction is empoyed: https://www.qrcode.com/en/about/error_correction.html

**Comment by PipBrewer** [comment]
@chelseagraham If this is still needed, I would suggest that this task goes to @lauritsf  now that he is working on the pinned insects. He will need a bit of background and context though and we will need to figure out the priority of this relative to his other tasks. Please advise regarding urgency/deadline and we will ensure it is fit in!

**Comment by chelseagraham** [comment]
This is being continued in another issue (#40)
https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/40
