### ISSUE TITLE
Request SIXTH run of barcode numbers from Specify team, create barcode labels, print and cut

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#100]
We are nearing the end of our fifth series of barcode numbers (001.732.708 through 001.742.707)

Prepare the next series of barcode labels for Pyralidae etc. digitization.

Past series of barcode numbers for reference:
Run 01: 001.648.939 - 001.650.938 (2.000 records issued 8 september 2023)
Run 02: 001.699.749 - 001.704.748 (5.000 records issued 8 november 2023)
[Run 03: 001.713.141 - 001.715.140 (2.000 records issued 11 januar 2024)](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/62)
[Run 04: 001.715.666 - 001.725.665 (10.000 records issued 31 januar 2024)](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/67)
[Run 05: 001.732.708 - 001.742.707 (10.000 records issued 19 april 2024)](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/81)

**Comment by chelseagraham** [comment]
Chelsea requested another 10.000 numbers from the Specify team.
Specify assigned the run 1772049 to 1782048 for this project.

**Comment by Gomismis** [comment]
Labels have been generated and are ready to print. I have divided the 10.000 numbers into 5 PDFs.
[NHMD_001772049-001782048-pages-1.pdf](https://github.com/user-attachments/files/16429011/NHMD_001772049-001782048-pages-1.pdf)
[NHMD_001772049-001782048-pages-2.pdf](https://github.com/user-attachments/files/16429012/NHMD_001772049-001782048-pages-2.pdf)
[NHMD_001772049-001782048-pages-3.pdf](https://github.com/user-attachments/files/16429014/NHMD_001772049-001782048-pages-3.pdf)
[NHMD_001772049-001782048-pages-4.pdf](https://github.com/user-attachments/files/16429015/NHMD_001772049-001782048-pages-4.pdf)
[NHMD_001772049-001782048-pages-5.pdf](https://github.com/user-attachments/files/16429018/NHMD_001772049-001782048-pages-5.pdf)

**Comment by nms419** [comment]
All 5 PDFs have been printed and placed in the cabinet in 411, and PDF 1 has been cut. 

I'll cut barcodes on Tuesdays the rest of August, so hopefully you won't have to stop digitising time to get more barcodes.

**Comment by nms419** [comment]
PDF 2 has been cut.

**Comment by nms419** [comment]
PDF 3 has been cut and placed at WORKPIOF0002, PDF 4 has been cut and placed at WORKPIOF0001 (by Matilde and Jesper, I think?)

PDF 5 has been cut and placed in the cabinet of 411. 

@chelseagraham could you request the next series of numbers from the Specify team?
