### ISSUE TITLE
Solicit feedback from Entomology Group on ALICE Broad Requirements

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#107]
NHMA & NHMD Entomology people, please provide any feedback in the the form of comments below or email to me chelsea.graham@snm.ku.dk by the end of the day on Monday 9 September.

[BroadRequirementsALICE_v1_20240723.xlsx](https://github.com/user-attachments/files/16847540/BroadRequirementsALICE_v1_20240723.xlsx)

**Comment by chelseagraham** [comment]
@PipBrewer I did not receive any feedback here nor via email.

**Comment by PipBrewer** [comment]
@chelseagraham No worries. After our 15th October meeting, we should go through spreadsheet and see which requirements we can achieve in version 1 and decide which have been agreed upon. Kim and Bhupjit should also feed into this. Other than this, this particular ticket can be closed.
