### ISSUE TITLE
Workstation Settings for different FOVs

### ISSUE THREAD

**Issue by nms419** [NHMDenmark/Pinned-Insects-workstation#108]
This issue is connected to issue #86, "Choosing a new FOV" in Shooting Pinned Insects Guide. We need a section in the guide that describes how to switch to a new FOV. These are the current outlines:

- When we start digitizing a new family a FOV should be selected to be used as the standard.
- The FOV should fit the biggest specimen in the group, even if this means some specimens will have a very big FOV. 
- Everytime a new FOV is chosen, a calibration image needs to be taken. 
- Because calibration images can be quite fiddly FOV should not change during an imaging session.
- Only the cameras height and depth should be changed, it should not be moved from side to side via it's mounting plate. 

We have 3 different sized angles for 3 different FOVs: Scarabaeidae, Pyralidae and Macromoths. 

We should have 3 different settings (camera height and depth) for each angle, so there is no doubt what the FOV is for a specific angle and it is easy to change between them. 

The current settings posted at the workstations now are: 
  Workstation 1
- Macromoths : 66,8 cm heigh, 15,3 cm deep
- Pyralidae: 54 cm heigh, 15,3 cm deep

Workstaion 2
- Scarabaeidae: 44,8 cm heigh, 11,2 cm deep
- Pyralidae: 53 cm heigh, 11,5 cm deep

**Comment by nms419** [comment]
Most of the FOVs work, but they do not match very well from station to station. Fx this is the Pyralidae FOV for both stations:





![Image](https://github.com/user-attachments/assets/030637db-577d-4245-b55b-9aea5866979d)



Scarabaeidae FOV for both workstations:




![Image](https://github.com/user-attachments/assets/2eb4902f-3d4d-4424-b490-7ca8f2ab22aa)


I've have suggested a new FOV for both angles for workstation two, which can be seen on the right side. 
These are not perfect because the were achieved by adjusting height and depth of the camera, when it would also need to be adjusted from side to side. 

The FOV for macromoths does not work on workstation two:


![Image](https://github.com/user-attachments/assets/8db728bc-c490-4678-b510-eb9ca311bb3c)

It could work if the angle could be pushed more towards the front of the stage, so the camera would not have to be so deep.

**Comment by chelseagraham** [comment]
Very very nice summary and depiction, @nms419 Thank you :)

I agree that the new settings that you propose are better and that we should adopt them, as well as document them in the guides and on the signs on the walls. 

The two lightboxes are slightly different in construction (both exact location of the camera hole and the sledges, thus we see some differences in the settings on the Kaiser copystand for our FOVs. @Gomismis and I will need to make a do a little work to see how we can fit the Macromoth FOV on WORKPIOF0002 seamlessly, so it is easy to change from one to another.

**Comment by chelseagraham** [comment]
I will add a note to include this information in the guide and sign on the Q3 updates ticket

I have made a ticket for work achieving macromoth FOV on WORKPIOF0002 here https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/109

**Comment by Gomismis** [comment]
I have wrote to carpenter Kim and requested if he could fix the macromoth FOV.
