### ISSUE TITLE
Q1 2025: Requests for refinements and new features for WORKPIOF (all)

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#111]
PLEASE ADD NO MORE REQUESTS TO THIS TICKET!
The new ticket for quarterly updates is this: #138 

Please add requests for updates, refinements and new features for the three labels off pinned insect workstations into this ticket.

These will be addressed and prioritised on a quarterly basis.

Next review will be in December 2024 / early January 2025 for implementation of agreed tasks starting in January 2025.
Discussed at digitizer meeting 10.12.2024, the following updates were decided:

- exchange aluminum rails in lightboxes for brass if it works in ALICE: #139
- create maintenance kit for workstations: https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/157

With the creation of separate issues for these updates, this ticket can be closed.

**Comment by RebekkaML** [comment]
@Gomismis suggested exchanging the aluminum rails that the sledges at PIOF01 and PIOF02 are currently running on with brass ones. For ALICE they already used brass in the hopes that it won't cause the black metal dust that the aluminum ones made over time. The dust is currently getting everywhere and when we tried to oil the rails it caused a sticky, black mass that made it even harder to use, so using brass instead might solve this issue. 
Charlotte, the Digitizer in Aarhus (who is a trained conservator), also mentioned that she thinks that the aluminum is not ideal here and other materials would cause much less dust.

**Comment by RebekkaML** [comment]
@chelseagraham suggested creating maintenace kits for the separate workstations that contain appropriate cleaning supplies etc. There is already a separate ticket for this (https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/157), but we should discuss in more detail what exactly we need.
