### ISSUE TITLE
Calibration Protocol for WORKPIO0001 and WORKPIO0002

### ISSUE THREAD

**Issue by nms419** [NHMDenmark/Pinned-Insects-workstation#114]
A new calibration protocol has been added to Shooting Pinned Insects Guide and a prototype of a calibration kit made and placed in the cabinet in 411. 

I've taken test images for the Pyralidae and Scarabaeidae FOV using the calibration targets from the calibration folder on the N drive.

The test images can be seen below and found at N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Pinned_insects\Calibration\CalibrationImages\WORKPIOF0002

The targets do not fill out the FOVs entirely. Currently they are resten on the imaging angle and the foam support. 

![Image](https://github.com/user-attachments/assets/9b9b2705-8631-4b41-a85b-35333ffa168d)
![Image](https://github.com/user-attachments/assets/b857f5b8-c8cb-4719-81c8-494d82c7c378)

**Comment by nms419** [comment]
@chelseagraham, I'm not sure what you need to make an proper assesment. Do the targets need to fill out the FOV? If so, larger targets and foam supports that surround the imaging angle needs to be made.

**Comment by chelseagraham** [comment]
Thank you for this, Sara! It is easy to assess with the visual depiction. As long as the target covers the angle, which should be all the area that we are concerned with in an image (the angle and the space within the angle where an insect will be pinned - insect should not go below the bottom of the angle nor further to the right than the end of the angle), then I think that all is well.

**Comment by nms419** [comment]
That's great! I'll leave the targets and foam supports as is then.
