### ISSUE TITLE
Create meeting series for collection managers and curators for pinned insects

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#115]
Please make sure Rebekka, PIp and Chelsea are co-hosts

Series should include:
General DaSSCo updates
Updates about pinned insects workstations and workflows: current digitisation, including targets and refinements needed
Updates about development
Questions from participants

Get update from Rebekka and Matilde about trip to Aarhus.

We need Q3 2024 stats sheets from everyone sending to info@dassco.dk.

**Comment by chelseagraham** [comment]
Added dates onto meeting series.
Added items to meeting agenda for 31 october.
https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/90
