### ISSUE TITLE
From Issues log 131: 11 error folders from WORKPIO0001 on the N drive

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Pinned-Insects-workstation#116]
On 26.08.2024, Sara Stenz wrote this on the issues log:

"Placed at N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\Temporary storage pinned insects\Ndrive_WORKPIOF0001\Error folders with compressed files 11  folders that have been unsuccesfully ingested from 23rd Oct. 2023 - 2nd Jan. 2024.  The folders have an uneven amount of TIFFS and RAWS, due to compressed TIFFS files.  Due to this, the folders can't be run through the IC at this stage. Khaled and Pip made aware over Slack on Aug. 26th 2024".

It appears that for every RAW file there are 2 TIFF files in these folders, one compressed and one normal version. Can these folders just be reingested, without the compressed tiffs, or are there more problems here?

**Comment by RebekkaML** [comment]
Reached out to Khaled (@k-zamzam) again, apparently there is also a naming issue in these folders and the easiest thing would be to redo the tiff conversion and then try to ingest again. I will start this today.

The folders are located here: "N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\Temporary storage pinned insects\Ndrive_WORKPIOF0001\Error folders with compressed files"

**Comment by RebekkaML** [comment]
I copied the folders from the N-drive back to the "WORKPIOF0001" folder on the PIOF01 PC, but only with the original RAW files inside. Then I started redoing the tiff-conversion in CaptureOne and Ingesting the folders. I did 6 folders today and everything looks like it worked well there. The remaining folders will be processed throughout the next days. 

So far, I have not deleted the old error folders on the N-Drive because I don't understand what went wrong there and don't know if we need to investigate this. @k-zamzam and @PipBrewer, do you have an opinion on this?

**Comment by k-zamzam** [comment]
Some of the error folders contain some .tif and .CR3 files. Have these .tif files been ingested again? Or are they duplicates?

**Comment by RebekkaML** [comment]
> Some of the error folders contain some .tif and .CR3 files. Have these .tif files been ingested again? Or are they duplicates?

I made copies of the entire folders and in those copies I redid the tiff conversion for all .CR3 and then ingested them. So all the .CR3 files have now been ingested again, but I didn't use the tiff files in those folders.

**Comment by RebekkaML** [comment]
All the error folders have now been successfully ingested again and if they are now longer needed for finding out what went wrong in the first place, the error folders on the N-Drive can be deleted.
