### ISSUE TITLE
Catch-Up Meeting 5 December 2024

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#118]
I will be on vacation 18 November - 4 December, returning on 5 December, so please add any items to discuss at this meeting here, @RebekkaML 
Need feedback from anyone who digitises using DigiApp: https://github.com/NHMDenmark/Mass-Digitizer/issues/526 

Update on planned changes to the DigApp (https://github.com/NHMDenmark/Mass-Digitizer/issues/548):
- two modes for entering data (start of sessions/ during session, see ticket above)
- add specimen counter
- toggle next to each field to make it sticky / non sticky
- add "delete entry" function

**Comment by RebekkaML** [comment]
This are the notes from the meeting:
[Entomology catch up_2024-12-05.pdf](https://github.com/user-attachments/files/18091590/Entomology.catch.up_2024-12-05.pdf)
