### ISSUE TITLE
Order label cameras and lenses for development of ALICE

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#126]
- [x] [Determine what quantities of which items are required](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/126#issuecomment-2444472121)
- [x] [Obtain quotes from vendors](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/126#issuecomment-2444566836)
- [x] [Make order](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/126#issuecomment-2462464728)

**Comment by chelseagraham** [comment]
###  Determine what quantities of which items are required

- [x] Sort out cameras and lenses, _29 October_

Cameras
**Canon EOS R10**
specs:
[EOSR10_specifications_5-22.pdf](https://github.com/user-attachments/files/17558864/EOSR10_specifications_5-22.pdf)
guide:
[c006.pdf](https://github.com/user-attachments/files/17558861/c006.pdf)

Canon EOS R10 cameras we have:
None

Lenses
**Canon RF 100 mm** 
specs:
[RF100mm_F2.8L_MACRO_specifications_FINAL.pdf](https://github.com/user-attachments/files/17571351/RF100mm_F2.8L_MACRO_specifications_FINAL.pdf)
guide:
[rf100f28l-macro-is-im2-eng.pdf](https://github.com/user-attachments/files/17571354/rf100f28l-macro-is-im2-eng.pdf)

Canon RF 100 mm lenses we have:
0044 - WORKPION0001 - on specimen camera
0045 - WORKPION0001 - on specimen camera
0059 - WORKPIOF0001
0214 - WORKPIOF0002
0217 - Repro set up in ZM room 137

- [x] Determine what peripherals are needed for cameras to operate smoothly, _29 October_

Power: AC adapter and DC coupler vs. USB power adapter
USB port needed for camera connection to PC, so ACDC better option to sustain power

Memory: [SD card](https://support.usa.canon.com/kb/s/article/ART182652?_gl=1*12xgdlz*_gcl_au*MjA3MjQwMTgzNy4xNzI0MjI3NTI2*_ga*Mjg5MDMwNTQxLjE3MjM3MjY2NTc.*_ga_RS2XCXV1Y7*MTczMDI4NzI5My4xNC4xLjE3MzAyODc1OTkuMTguMC4w*_fplc*TCUyRjlIZTQ4dVdJajVRc3RFWmRZWnk5c3AxMHEycDlnSkxXMHVaMVUlMkZWQVZqekh3Zm83MW1NVDhVOE5xVkVsYk5GZTlBZ0dYajc5MlQzMCUyRmxYYTdzbyUyRmlZSDJmRDhDQmolMkJmWmxHMWVpUTRHNU5sVTFVeEF2d3pPVDVneHJtQSUzRCUzRA..)

- [x] Make list, _29 October_

**TO ORDER**

- 4 [Canon EOS R10 camera bodies](https://store.canon.dk/canon-eos-r10-mirrorless-camera-body/5331C044/)
- 4 [Canon RF 100mm F2.8L MACRO IS USM lenses](https://store.canon.dk/canon-rf-100mm-f2-8l-macro-is-usm-lens/4514C005/)
- 4 [Canon DR-E18 DC couplers](https://store.canon.dk/canon-dr-e18-dc-coupler/0250C001/)
- 4 [Canon AC-E6N AC Adapter](https://store.canon.dk/canon-ac-e6n-ac-adapter/1425C007/)
- 4 USB-C Cables (TETHER TOOLS USB-C TO USB-C 4,6M, or similar)
- 4 SD cards (SANDISK SD 128 GB EXTREME PRO 200MB/S V30, or similar)

**Comment by chelseagraham** [comment]
###  Obtain quotes from vendors

- [x] Solicit quotes from vendors, _30 October_
- - [x] Goecker: Carsten Iversen, carsten@goecker.dk
- - [x] Scandinavian Photo: Peter Steenberg, peter.steenberg@scandinavianphoto.dk
- - [x] Photografica: mail@photografica.com
- - [x] Kamerahuset: https://www.kamerahuset.dk/contact/index/
- [x] Follow-up with vendors from whom I have not received quotes, _30 October_, _4-7 November_

- [x] Upload received quotes 
- - [x] Goecker: **58.406,00 DKK**,  c.14 days [1232538_SNM.pdf](https://github.com/user-attachments/files/17590241/1232538_SNM.pdf)
- - [x] Scandinavian Photo: **58.865,60 DKK**, their best bet before Christmas [Tilbud - Københavns Universitet - Q0015577 - 2024-10-31 - 13-50-32.pdf](https://github.com/user-attachments/files/17590283/Tilbud.-.Kobenhavns.Universitet.-.Q0015577.-.2024-10-31.-.13-50-32.pdf)
- - [x] Photografica: not possible for them to fulfill [RE: Quote for equipment - Autumn 2024.pdf](https://github.com/user-attachments/files/17618948/RE.Quote.for.equipment.-.Autumn.2024.pdf)
- - [x] Kamerahuset: **55.972,58 DKK** excluding 4 USB-C cables, their best bet is 4/5 weeks (+ c.2.000 DKK), awaiting lead time [Tilbud 1320.pdf](https://github.com/user-attachments/files/17645696/Tilbud.1320.pdf)

- [x] Compare quotes and select vendor, _7 November_
**1 Goecker - can deliver all of the items within 14 days for 58.406,00 DKK**
Goecker is able to deliver all items the most quickly at competitive cost.
2 Kamerhuset - cannot deliver all of the items and cannot guarantee delivery within 14 days (55.972,58 DKK excluding 4 USB-C cables, so add + c.2.000 DKK)          
3 Scandinavian Photo - can deliver all of the items by Christmas (58.865,60 DKK)
X Photografica - cannot fulfill this order

**Comment by chelseagraham** [comment]
### Make order

_7 November_ - emailed Carsten Iversen at Goecker to place order
_8 November_  - order confirmed

Order Confirmation: 
[Ordrebekraeftelse_1232538.pdf](https://github.com/user-attachments/files/17676610/Ordrebekraeftelse_1232538.pdf)

expected within 14 days

**Comment by Gomismis** [comment]
I have picked up 2 out of 4 cameras and lenses + their accessories. The last two cameras, lenses and adaptors will most possible arrive Monday next week and i will pick them up the following Tuesday.

**Comment by Gomismis** [comment]
All four cameras and lenses are picked up from Goecker (monday 2nd of december). The only componetns we’re missing now is two AC adaptors for the Canon R10s (Goecker will contact us when they are ready for pick up). In the meantime, I’ve been using battery packs (two in the cameras and two charged ones in the chargers).

**Comment by chelseagraham** [comment]
two AC adaptors for the Canon R10s outstanding

**Comment by Gomismis** [comment]
I've picked up the last two AC-adaptors and placed them in 411. The order is now completed.
