### ISSUE TITLE
Lens selection for labels

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#13]
- [ ] Decide on lens for upper label camera
- [ ] Decide on lens for lateral label cameras
- [ ] Test and get feedback from examples

**Comment by chelseagraham** [comment]
Lenses selected for Raspberry Pi label cameras

**Comment by chelseagraham** [comment]
Lenses selected:

1 Barcode lens: (8 mm 1:14 Ø25.5 Tamron 070195) 100 mm
4 Label lenses: (25 mm 1:14 Cosmicar/Pentax C2514-M) 110mm
