### ISSUE TITLE
How to deal with multispecimen objects

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#16]
If there are multiple specimens on a pin - presumably only one barcode needs to be applied. However, we should also presumably flag this as a multispecimen object. Should the digitiser count the number of specimens or could we simply add a container to this record?

**Comment by chelseagraham** [comment]
Pip and Chelsea discussed and decided that in the case of a multispecimen object, a Digitizer will 
attribute one barcode to the pin
click the radio button for MSO in the Digi app
write in the notes field "Multiple specimens on pin"

The Digitizer won't count the number of specimens on the pin. 

A single container ID will be created in connection with clicking the MSO button in the app although there will be a sole record with that ID at this time.
