### ISSUE TITLE
Develop in-house capability for printing aligned double sided labels

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#18]
Anders and Roberta to hold some more programming sessions to enable him to tailor code for printing the labels double-sided and aligned

**Comment by PipBrewer** [comment]
Transferred from [Develop in-house capability for printing aligned double sided labels](https://github.com/NHMDenmark/Mass-Digitizer/issues/236) to put in correct repo

**Comment by PipBrewer** [comment]
@lauritsf to add details of where documentation and instructions are here and then pass to Chelsea who is looking into printers

**Comment by PipBrewer** [comment]
A large part of this issue is being documented in  Requirements for barcodes #40  in the Pinned Insects workstation Repo

**Comment by chelseagraham** [comment]
Program functional for both NHMA and NHMD
Experimentation with alignment continues with our in house printer
