### ISSUE TITLE
Source barcodes for mass digitisation

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#20]

**Comment by PipBrewer** [comment]
Transferred from [Figure out how to source the barcodes en masse#53](https://github.com/NHMDenmark/Mass-Digitizer/issues/53) to put in correct repo

**Comment by lauritsf** [comment]
It might be worth exploring laser cutting the printed sheets.
It could be an idea to speak to some local laser cutting shops about their precision for cardstock as well as test it.

**Comment by chelseagraham** [comment]
We have purchased a Canon imagePROGRAF PRO-1000 printer with carbon pigmented ink and have printed labels using the label generator program that Roberta created and Laurits customzed for NHMD and NHMA. Matilde experimented with how to get alignment adjusted. Jesper and Chelsea cut approximately 2000 labels worth into strips on a paper cutter. The labels are dispensed from a pin and clipped off as needed during digitization.


Label printer: https://www.proshop.dk/Printer/Canon-imagePROGRAF-PRO-1000-Fotoprinter-Farve-Blaek/2719404?utm_source=google&utm_medium=cpc&utm_campaign=searchengine&gclid=Cj0KCQjw5f2lBhCkARIsAHeTvlihkHDUdljMYeKYBlA0SlWP-vc4-fjUElF2VZPYnPWhFG-ZtM7hSokaAjxREALw_wcB
((Printer for labels:
https://www.canon.dk/printers/inkjet/pro-photo-printers/imageprograf-pro-1000/#specifications
specs: https://www.canon.dk/printers/inkjet/pro-photo-printers/imageprograf-pro-1000/specifications/
blacks Jan has tested in alcohol: MBK/PBK
Canon confirmed that the ink is carbon pigmented ink
https://www.usa.canon.com/shop/p/pfi-1000-matte-black-ink-tank
https://www.usa.canon.com/shop/p/pfi-1000-photo-black-ink-tank
further links from Canon
https://www.usa.canon.com/pro/printers/pro-ink-paper
https://www.usa.canon.com/support/p/imageprograf-pro-1000 ))
