### ISSUE TITLE
Source stable mounting solution for 1 Raspberry Pi Zero 2 W camera for imaging labels from top

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#23]
Consider mounting to Kaiser camera carrier or constructing scaffolding from Bosch Rexroth aluminum profile system

**Comment by chelseagraham** [comment]
@Gomismis to begin research into this for a v.1 static ALICE set up for Danish Beetles beginning in early November

**Comment by chelseagraham** [comment]
See https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/22
