### ISSUE TITLE
Feedback on area/FOV for specimen labels

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#27]
After #26 is complete:
- [x] Take example images for feedback (CMs and curators and for OCR)
- [ ] Figure out protocol if encounter labels which won't fit in area and seek feedback

**Comment by chelseagraham** [comment]
Example of stage and angle presented to CM in September 2023 in Digitization Catch up Meeting. 
At this point, there is ample space for labels on the angle. 
As with labels-on workflow, if there is not room for all labels, a priority will be given to the bottom 3 labels.
