### ISSUE TITLE
Confirm configuration of all cameras and PIs and enough room to manipulate specimens

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#29]
Map out physical set up (blueprint), check feasibility and what gets in the way (including lateral Rasberry PIs)
Take some example images
Consider how to affix cameras and what we need in order to create

**Comment by chelseagraham** [comment]
Raspberry Pi focal distances from end of lens to subject for Canon FOV #1 (Canon 3.6 cm x 2.4 cm field of view, 284 mm focal distance):
Cicada 110mm
Dragonfly 100 mm
Ant 120 mm
Beetle 120 mm
Earwig 160 mm

Cicada
![pieye-cicada](https://user-images.githubusercontent.com/108529653/231777089-08a5c752-3401-4095-82e9-2e67d838e4fd.jpg)
Dragonfly
![pieye-dragonfly](https://user-images.githubusercontent.com/108529653/231777256-ce3f458e-5b12-4a2f-8c9f-c18889c020fd.jpg)
Ant
![pieye-ant](https://user-images.githubusercontent.com/108529653/231777317-f086a487-4d6f-48c9-978c-cd12ce4bdf23.jpg)
Beetle
![pieye-beetle](https://user-images.githubusercontent.com/108529653/231777376-be162230-2170-400c-b8ec-f94620f43cda.jpg)
Earwig
![pieye-earwig](https://user-images.githubusercontent.com/108529653/231777433-78082671-029c-44a7-9df1-50c73ca3d3a9.jpg)

Canon Dorsal
![Untitleddorsal](https://user-images.githubusercontent.com/108529653/231777921-46910bfb-2ce5-4adf-a65a-4ff99a28c9dc.png)
Canon Lateral 
![Untitledlateral](https://user-images.githubusercontent.com/108529653/231777794-d92b9205-3b9d-4488-86e6-577231037041.png)

**Comment by chelseagraham** [comment]
Lenses selected:

1 Barcode lens: (8 mm 1:14 Ø25.5 Tamron 070195) 100 mm
4 Label lenses: (25 mm 1:14 Cosmicar/Pentax C2514-M) 110mm

**Comment by chelseagraham** [comment]
An all-Canon camera array has been selected for the first version MVP of ALICE
