### ISSUE TITLE
Create set up and requirements for simplified workstation

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#36]

**Comment by chelseagraham** [comment]
Workstation: copy stand with camera, lens, lightbox (created by Kim Nielsen from the SNM woodshop) with ring light and two godox panel lights, monitor, barcode reader, laptop with app all set up in 411. 

Computer ordered via KUIT

Matilde working on stage

**Comment by chelseagraham** [comment]
Matilde has created the stages for NHMD and NHMA for the FOV for pyralidae. We have the requirements for the stage for the macro moth FOV.

All materials were sourced and assembled. A workstation was delivered and set up at NHMA and has been implemented at NHMD. A second workstation is being assembled at NHMD.
