### ISSUE TITLE
Design Stage for Pyralidae (4 cm and below) for simplified set-up

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#38]
Design stage 
-     Determine size requirements
-     Research materials
-     Create options

**Comment by chelseagraham** [comment]
Determine size requirements

![Image](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/108529653/f3b365f9-7f82-41cd-8678-be2b55dd2d72)

**Comment by chelseagraham** [comment]
Matilde working on stage. 

Some things to adapt / consider
- create many stages and tops to allow for efficiency (next specimen being set up while the prior is being imaged)
- decrease the height of bars which hold the labels:  reduce to 1 cm will better allow a secure hold of insects that are mounted lower on the pin
- ensure the legs are the same length or slightly longer than the part holding the bristles so that the stage is very stable 
- some divots in the sliding tray in the lightbox, or another alternative to keep the stage in place, but will enable changing stages easily

**Comment by Gomismis** [comment]
I'm at the moment waiting for the first print to be done for testing. I have only printed 1 stage and label holder to begin with, but I can easily get more printed when I have tested the full setup. Furthermore, I will have the gray cards laser cut so they fit the stage. and last but not least I will buy a new type of silicone mat, that isn't as shiny as the one I first ordered.

**Comment by chelseagraham** [comment]
Matilde has created the stage for Pyralidae. 

@Gomismis please close ticket once stages have been finalized and created for all workstations (NHMA, NHMD 1 and NHMD 2)
