### ISSUE TITLE
Scope and source barcodes for NHMA

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#39]
We need at least a reasonable short-term solution

**Comment by lauritsf** [comment]
I can look further into how much data we can realistically encode and more. However, I need to know more about the needs and requirements for the data to encode in the barcodes. @chelseagraham

**Comment by lauritsf** [comment]
Reference to discussion about NHMA labels scope: [NHMDenmark/Pinned-Insects-workstation#40 (comment)](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/40#issuecomment-1645570272).

**Comment by chelseagraham** [comment]
Solution - DaSSCo to generate labels for NHMA and send to them because printer and knowledge of how to use the label generator is based at NHMD
