### ISSUE TITLE
Requirements for barcodes

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#40]
Work with Laurits/z to establish if specifications of collections managers and curators for barcodes also work for digitisation.

Requirements:

- Confirm maximum/preferred size of barcode labels
- Confirm what ideally is encoded
- Check if focus affects reading of barcode by program AND scanner
- Check if angle of data matrix affects reading of barcode by program AND scanner
- Check if data matrix not being flat affects reading of barcode by program AND scanner
- Test on actual examples and look at error rate for program AND scanner

**Comment by PipBrewer** [comment]
@chelseagraham and @lauritsf Please could you feedback and document directly into this ticket?

**Comment by lauritsf** [comment]
I have reviewed the details mentioned in [this GitHub issue](https://github.com/NHMDenmark/Mass-Digitizer/issues/52#issue-1302138460) and discussed the constraints we need to consider together with @Andersillum.

**Label/tag size**:
- Width: 12mm
- Height: 5mm

To ensure the specimens fit back into their boxes, it's important to keep the label/tag size within these dimensions. Some specimens are very small, and larger tags/labels would pose difficulties.

**Datamatrix size**:
- Maximize the size while maintaining a "silent zone" of two white modules around it.

We should aim to make the datamatrix as large as possible without compromising the space needed for the "silent zone." Rectangular datamatrices are also an option, but we must strike a balance with the accompanying text.

**Border around the label?** No border, unless for printing purposes.

Including a border would consume valuable space without offering noticeable benefits. However, when it comes to printing, having a border between labels can be useful for visual separation.

**Text**:
- Font: [Inconsolata](https://fonts.google.com/specimen/Inconsolata)
- Size: 3.5pt-4pt
- Placement: 1.3mm from the side, with equal vertical spacing.

The text on the label should be legible in small prints and suitable for OCR. It's preferable to use an open/free font like Inconsolata, although other fonts are also acceptable. Keep in mind that system fonts like Arial may not be open/free, but users with Microsoft/Adobe software typically have licenses. With this font size, we can comfortably fit 2 or 3 lines while maintaining readability. The spacing of 1.3mm from the side provides enough room for the pin dot. 

**Pin dot**:
- Radius: 0.1mm
- Placement: halfway between the top and bottom, spaced 0.7mm from the side

The pin dot serves the purpose of enabling easy piercing of the label with a needle. The placement has been copied from the details provided in [this GitHub issue](https://github.com/NHMDenmark/Mass-Digitizer/issues/52#issue-1302138460).



![example_front](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/8676d008-09fc-4d20-be43-caa8c4fa4efb)
![example_back](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/59b4e3d1-9bb5-4952-bf0b-fa6d2e9e4e69)

**Comment by Andersillum** [comment]
It looks good :) Can you try making the text bold? or does it get to big then?

Which kind of data is in the datamatrix? Can we get NHMD1234567 (or how many digits is needed). It would make the datamatrices much more useful for scientific studies (in excel for example), registration etc. with a barcode scanner if there is NHMD in it. I know Specify 6 ignores the leading NHMD and only searches for the catalog number when looking up specimens, I hope specify 7 does the same.

> **Border around the label?** No border, unless for printing purposes.
> 
> Including a border would consume valuable space without offering noticeable benefits. However, when it comes to printing, having a border between labels can be useful for visual separation.
> 

The main purposes for the border is for for cutting.

**Comment by lauritsf** [comment]
> Can you try making the text bold? or does it get to big then?
I will play around with the text and find good balance :)

> Which kind of data is in the datamatrix? Can we get NHMD1234567 
As we discussed yesterday Specify 7 will not ignore the characters anymore, and will now be up to 9 digits, with leading zeros.
I have now been informed that they should contain 9 digits (including leading zeros, eg. 003456789), but I will also be testing including NHMD (eg. NHMD003456789).

> The main purposes for the border is for for cutting.
That is what I should have written ;)

**Comment by chelseagraham** [comment]
In our planning meeting this AM; Pip, Matilde and I discussed that Laurits is making two versions of the labels with the data encoded as he described in the comment above. 

Matilde or I will take at least 100 images of each of the kinds of labels on the draft stage for Laurits to run though a software to detect the data matrices. We will also test the barcodes by scanning them into Excel and note the amount of time it takes to scan them in successfully. (I don't anticipate any errors in the numbers read, just in the amount of attempts to successfully scan the barcodes with NHMD012345678 encoded).

**Comment by lauritsf** [comment]
**Text:** (Update)
- Font: [Inconsolata](https://fonts.google.com/specimen/Inconsolata) (ExtraBold)
- Size: 4pt
- Placement: 1.3mm from the side, centrally, with equal distance between top and bottom. line spacing of 0.5mm

With 9 digits, the numbers might be slightly too long with this font size.

**Printing:**
Printing the sides one by one with manual feeds seems to decrease the displacement between labels on the front and back.
It should be noted, that it is not entirely robust, but I was able to get relatively good results first try with the cardstock.

| Top                                                                                                        | Bottom                                                                                                        |
| -------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| ![Image 1](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/f805d567-20f6-4104-8865-848b4f34bfd5) | ![Image 2](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/16443420-3832-437e-aafb-ff40b1718214) |

**Comment by chelseagraham** [comment]
Super! Thank you for making the labels with landscape orientation, Laurits!

**Comment by lauritsf** [comment]
I just thought, however, the text ought to be written in the direction away from the needle, however.

**Comment by lauritsf** [comment]
Following the discussions with @Andersillum, @PipBrewer, and @chelseagraham, I have generated labels with the following specifications:

- **Label Size**: 
  - Dimensions: 12x5mm
  - Border: An added 0.5mm grey border for ease in cutting and to account for any minor misalignments during double-sided printing.

- **Font**: 
  - Type: 'Inconsolata extra bold'
  - Size: 3.7pt

- **Numbering**: 
  - Format: Each label contains a unique number composed of 9 digits. These numbers include leading zeros where necessary.
  - Selection: Numbers were randomly chosen.

- **Label Text Layout**: 
  - Content: The layout includes 'NHMD' at the top and the number (with leading zeros) at the bottom.
  - Placement: The text is 1.3mm from the side, with a 0.5mm line spacing in between.
  - Alignment: The text is positioned equidistant from the top and the bottom.

- **Pin Dot**: 
  - Size: The dot has a radius of 0.25mm.
  - Location: It is centrally located with its center halfway between the top and bottom, and 0.7mm from the left side.

- **Datamatrix**: 
  - Shape: The matrix is square.
  - Size: The size is optimized to be as large as possible while still maintaining a 2 module wide silent zone around it.
  - Content: The matrix data corresponds to the number (with leading zeros), with an optional 'NHMD' prefix.

- **Rendering and Printing**: 
  - Rendering: The labels have been rendered at 600 dpi.
  - Printing: Printed on double-sided A4 sheets. Each sheet contains 100 labels for testing purposes, though more could fit on a single sheet.

- **Design Modification**: 
  - Modification: The front and back of the labels are now identical to improve consistency and ease of use.

For review, I have included the label data and the generated labels in the links below:

- [label_data.csv](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12048187/label_data.csv)
- [NHMD123456789.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12048188/NHMD123456789.pdf)
- [123456789.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12048186/123456789.pdf)

**Comment by chelseagraham** [comment]
@Gomismis and I have tested the labels Laurits created. The barcode labels scanned without any errors or delays. All barcodes were also photographed. 

The files are at the following location:
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Pinned Insects Working Data/BarcodeLabelTesting_LauritsModSetup :D

**Comment by lauritsf** [comment]
## Label Photos and Sets

For each label in [NHMD123456789.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12048188/NHMD123456789.pdf) and [123456789.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12048186/123456789.pdf), there is a top view photo of a specimen with the label to the side.

In total, there were 2 sets of 100 labels each.

## Example Pictures

| Example picture | ![Example picture](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/21dcd8bd-f59e-49dd-b632-99df639e3595) |
|-----------------|---------------------------------------------------------------------------------------------|
| Example crop    | ![Example crop](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/f6ed8a84-94d7-46c0-896d-38c8e520734e) |

## Label Visibility and Orientation

In all of the pictures, the label is in clear view and in focus. In some cases, the label has been rotated.

## Decoding Process

In all of the pictures, I was able to decode the datamatrix, and there was a 1:1 correspondence with the expected values. However, to actually detect and decode the datamatrices, it was necessary to reduce the resolution of the pictures and crop the general area where the datamatrix is expected. This is not due to bad image quality but instead a limitation with the decoders.

`zxing-cpp` was used as a first-line decoder, and `pylibdmtx` was used where the first failed to decode.

## Conclusion and Next Steps

We can (carefully) conclude that the label dimensions are sufficient for this specific setup, although more work is needed to investigate other angles and perspectives/focal lengths, as well as the post-processing/decoding.

**Comment by chelseagraham** [comment]
This is great and this is with labels printed on a general KU printer. 

We will pursue a higher resolution printer, but it does not seem like a priority for testing the data matrix detection.

**Comment by Andersillum** [comment]
@lauritsf It looks really good. Should and could we fix one of the Raspberry Pi and try with pictures of the datamatrix from a Pi camera?

**Comment by lauritsf** [comment]
@Andersillum I will be working on getting the raspberry pi cameras up and running as well this or the coming week.
I have identified identified a few inconsistencies with the NHMDenmark/Pi-Eye repo, which is causing at least one of the problems we are experiencing.
Then we could look into expanding to angled shots with the Raspberry Pi cameras.

**Comment by chelseagraham** [comment]
@Andersillum and I discussed how Specify may dictate label requirements with @FedorSteeman and determined the following:
Labels should NOT have NHMD encoded in the data matrix
Labels should contain 9 digits (including leading zeros) encoded in the data matrix

Anders proposes to have labels display numbers without leading zeros (while still maintaining numbers of a full 9 digit length  encoded in the data matrix).

**Comment by chelseagraham** [comment]
I met with Simon from NHMA to discuss their labels today. 

The most important thing for them is to maintain the size of the label (19 mm x 14 mm) and the placement of the pinhole dot. 

They prefer the orientation of the text on the label as presented, but could drop 'ENTOMOLOGY' from the label and do not care about the number being bold. All text can be the same style and size. The 9 digit catalogue number being encoded in the data matrix is ok with them. They do not have a preference if the label displays the number with or without leading zeros. They would like a double sided label. 

![NHMA_DMex](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/108529653/e033658d-4654-4215-b93c-5fed6cd5ccd9)
[Insekt (Etiket) - Simon.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12124917/Insekt.Etiket.-.Simon.pdf)

**Comment by chelseagraham** [comment]
Emailed NHMA (Thomas, Hans, Simon) to confirm that encoding solely the nine digit number is ok with the institutional numbering system on 1 August to inquire.

**Comment by lauritsf** [comment]
**Related Discussion:** [Link to Issue #40](https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/40)

**Comment by chelseagraham** [comment]
NHMA would like to have the opportunity to see barcode labels before they are finalized

**Comment by chelseagraham** [comment]
Hans response to the inquiry: 

[SV: Insect barcode labels.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/12303043/SV.Insect.barcode.labels.pdf)

>>
Like Simon answered, all the below sounds good to me.
Except maybe if we could have labels without leading zeroes in the catalog number. We don’t have leading zeroes in any of the existing collections or labels.
 
I think I have told Pip before, but we do have several collections starting with CatNo 1. We have added acronyms to avoid errors. Eg NHMA ENT 1 for entomology collections CatNo 1, NHMA VERT 1 for vertebrate collections CatNo 1 etc.
<<

Clarifying with him if he means that they would prefer excluding leading zeroes written on the label but it is ok embedded in the data matrix. Copying Pip.

There is confirmation on the repeat of the catalog numbers in different divisions.

**Comment by lauritsf** [comment]
### NMHD Text Justification for Pinned Insect Barcode Labels
![label_left_right](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/04a88eba-5b4c-471b-b104-00914cbdbda9)
![label_right_adjusted](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/60dd434c-44b3-4513-9659-cf911d58c641)
![label_left_adjusted](https://github.com/NHMDenmark/Pinned-Insects-workstation/assets/79061425/bbee26ef-06d1-4652-acb8-5f0bdd74f43e)

#### Consulted:
- Jan Pedersen, Sree Gayathree Selvantharan, and Alexey Solodovnikov (Anders Alexander Illum and Chelsea Alene Graham were cc'd, but both are on leave)




#### Decision:
- The team decided on the **right adjusted** version of the label template.

#### Laurits Fredsgaard Larsen's Comments:
- Right aligning ensures 1’s, 10’s, 100’s, etc., are consistently placed.
- For low numbers, the NHMD may appear to float on the left side of the label.
