### ISSUE TITLE
NHMD Entomology - Storage Locations

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#42]
Get confirmation from collection managers at what level in the storage tree hierarchy they would like in the app. This could be Zoological Museum, room number, row number etc. Alternatively, the digitisers could leave this blank.

**Comment by PipBrewer** [comment]
@chelseagraham please bring it up at the monthly meeting.

**Comment by chelseagraham** [comment]
In our Entomology DaSSCo Digitization Catch-up meeting on 25 October, the group unanimously agreed (NHMA and NHMD both) that as the collections are organized by Linnaean hierarchy and rearranged at times, no storage lcoations are required for entomology collections. This is documented in the meeting notes sent via email on 26 October.
