### ISSUE TITLE
NHMD Entomology - Taxonomy Author and Year #366

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#43]
#366

What is the issue ?
Author and year are not available to enter into the app

**Comment by PipBrewer** [comment]
The taxon spine which the digitisation app draws on is derived from Specify. Once the collection managers send the taxon spreadsheet to me for importing - this goes into Specify. If author names etc are included in that, they will be added to Specify. The app then draws that information from the taxon tree in Specify and will link with it. However, not all information is visible in the app (it is simplified). However, if the author names and year are in the taxon records in Specify, they will be visible associated with the records created by the app. In the meantime, there is a ticket in the mass digitisation github board (#154) which requests that this information (and teh higher taxonomy) be visible in the app. This would require coding and rearrangement of the app. It is currently listed as priority 4 (1 being highest priority). If collection managers and curators would like it to be higher, they need to let Pip know and what the use case is (e.g., why it is important). @chelseagraham to liase with them on this and report back. If they are happy to leave this as priority 4, this ticket can be closed.

**Comment by chelseagraham** [comment]
Emailed Jan, Sree, and CC Anders (vacation) on 1 August to inquire.

**Comment by chelseagraham** [comment]
No one has ever responded about this. It is a priority 4 and therefore the issue will be closed.
