### ISSUE TITLE
Design Stage for Macromoths (15 cm and below) for simplified set-up

### ISSUE THREAD

**Issue by Gomismis** [NHMDenmark/Pinned-Insects-workstation#48]
Based on measurements below, create stage for Macromoth FOV. 

Once established, document in the following ticket 
https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/57

**Comment by chelseagraham** [comment]
The largest FOV that can be accomodated in Kim's lightbox measures a total size of 15.5 cm x 10.2 cm (including the border at the top and left). The area of interest (area available) for a specimen therefore measures 13.5 cm x 8.2 cm. The focal distance for this FOV is 61 cm to focal plane and 62 cm to base of gray card.

**Comment by Gomismis** [comment]
The macromoth stage is created. The 3D-files and technical drawing is located in folder: 
N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Pinned_insects\technical drawings and 3D-models

**Comment by chelseagraham** [comment]
@Gomismis Have stages been created for the Macromoth FOV (angle on graycard) and if not, what is necessary in order to create these?
