### ISSUE TITLE
Set up Mac

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#5]
- [x] Request common user log-in 
- [x] Plug in and get set-up

**Comment by PipBrewer** [comment]
Waiting for log in from IT

**Comment by chelseagraham** [comment]
On 23 February, IT inquired about which other computers would use the general DaSSCo01 user log-in that was requested on 15 February (Incident 245523). I gave them the number for the NHMD Herbarium workstation PC.

**Comment by chelseagraham** [comment]
On 1 March, added a comment to check status with IT.

**Comment by chelseagraham** [comment]
[DaSSCoCommonUsernamePW.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/10862479/DaSSCoCommonUsernamePW.pdf)

**Comment by chelseagraham** [comment]
Set up Mac. Need to order peripherals (mouse and keyboard, but can maybe borrow others for now)
