### ISSUE TITLE
Set up second simplified workstation at NHMD

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#54]
- [x] Procure components
- [x] Set up physical workstation
- [x] Set up PC and download programs
- [x] Create stages
- [x] Set up camera

**Comment by chelseagraham** [comment]
Jesper and Rebekka began setting up second workstation in room 411 at NHMD

**Comment by chelseagraham** [comment]
@Gomismis please take a look at lights and sand and saw so they fit, when you have a chance.

**Comment by Gomismis** [comment]
I have installed all the lights now. All 3D-prints are printed, I just need to assemble them, I will do this before I go on vacation
