### ISSUE TITLE
Pinned Insect Tray Grid (Issue Log Nr 24)

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#56]
Rebekka Lesske writes:
details:
It would be good if we had something to mark the positions of the pins of the insects in the new trays we put them in, so the 2 columns are in the right positions. Need 1 for to be digitised tray and one for digitised tray. An example would be a 3D printed black or wooden block with regular marks on it so can see at what intervals the pins are in the tray at a glance.

**Comment by chelseagraham** [comment]
Discvuss with colleagues, experiment with mm graph paper, or any materials you see fit to devise a helpful guide for repinning insects in the different size unit trays.

Make recommendations on how to make these guides permanent (building, 3D printing, etc.) and provide 'blue prints' (dimensions, and features that would need to be modeled or considered in creation)

@nms419 Please work on this when you can and let's check in about this on 10 November.

**Comment by Gomismis** [comment]
I have made a prototype in autodesk inventor and will continue develop after I return from vacation.

**Comment by chelseagraham** [comment]
Digitizers have used foam and pins for this purpose.
