### ISSUE TITLE
Decide on FOV for beetles (or Danish beetles) and pyralids: Dorsal view

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#6]

**Comment by PipBrewer** [comment]
Investigate other digitisation programs and what doing
Results of Pip's research
Incoporate feedback from stakeholders and decision so far
What is ideal FOV based on this and including at least colour
Test for minimum and maximum sized specimens within that range and results - what is the resolution etc 
Get feedback from stakeholders

**Comment by PipBrewer** [comment]
Summary of useful bits for us from paper: Ferns, P. N. & Jervis, M. A., 2016. Ordinal species richness in insects-a preliminary study of the influence of morphology, life history, and ecology. Entomologia Experimentalis et Applicata, 1–15. DOI: 10.1111/eea.12417. 

Table 1 Body lengths of North American, European, and South African species of insects.
Note, that for particularly Lepidoptera, when wings are spread out - width may well exceed length

Order	No. of species	Mean (mm)	Body size range (min)	Body size range (max)
Lepidoptera	180,000	19.5	1	125
Diptera	150000	8.7	2	30
Hymenoptera	115000	9.9	1	78
Coleoptera	350000	6.1	1	96
Hemiptera	80000	8.6	1	55
Orthoptera	24000	33.2	7	80


Also, note that I visited the insect digitisation at NHM (London). Here are a couple of notes – 

For the LABELS OFF workflow that are 2 set ups (note that this set up can also be used for slides):
Larger set up – 27 cm ring light size – photo with light off
Keep specimens at same height – series of straws and different heights of platforms.

**Comment by chelseagraham** [comment]
![Image](https://user-images.githubusercontent.com/108529653/221579401-70c00e02-e560-4c2f-aa01-015b790276ec.jpg)

### **Dorsal FOV**

Testing hardware:
Canon EOS R5 camera
Canon RF 100 mm F2.8 L Macro IS USM lens

Testing software:
Canon EOS Utility

Camera parameters: 
Av
f/16
ISO 100
AWB

Image composition:
Center insect in frame
Attempt to include scale and color checker

**#1 SMALLER RANGE (up to 2.5 cm)**

1x FOV 3.6 cm x 2.4 cm 
Camera set at 24.3 cm at bottom of Kaiser camera carrying carriage

Mock-up scale 1 cm x 0.4 cm
ISA Pico Color Target 1.0 cm x 1.1 cm

Stage 1 cm foam pinning insect, 3 cm height of plane, total footprint 12 cm x 8 cm 

![Image](https://user-images.githubusercontent.com/108529653/221579602-4279f3b7-106d-436f-910b-e9a9bc783800.jpeg)
Stage with FOV and scale mock-up

Insect Images

![Image](https://user-images.githubusercontent.com/108529653/221580361-c3d972cd-71d1-4f94-ae6c-911b2884c48d.JPG)
14_3_1982_UtterslevMose

![Image](https://user-images.githubusercontent.com/108529653/221580869-625d0966-abd9-4406-b6e7-a13332f70039.JPG)
16_9_1980_Marselisborg

![Image](https://user-images.githubusercontent.com/108529653/221581065-ff50770f-aacc-466f-b384-429b864f5f4a.JPG)
RedBeetle_1pt2cmlong_0pt7cmwide

**Comment by chelseagraham** [comment]
QUESTIONS FOR COLLECTIONS MANAGERS AND CURATORS

•	Are the images of the very small beetles (below 1 cm) usable for the #4?
•	Could we adopt #4 settings for Pyralids and #1 settings for the first years of imaging Danish beetles?
•	Could we then adopt #2 for drawers of larger beetles that may be skipped after the first few years and #3 for extreme cases?

**Comment by chelseagraham** [comment]
COLLECTIONS MANAGERS’ INPUT

**Anders** suggests having a FOV for Pyralids (up to 3.8 cm) and one for the majority of Danish beetles (up to 2.5 cm). In the beginning of the Danish beetle collection, roughly a half of a million specimens consecutively are quite below 2.5 cm in size. Anders suggests skipping certain families (can be up to 7.0 cm in width or have antennae which require a lot of real estate – for example Cerambycidae) or drawers within families with a lot of variation (for example, Hydrophildae where 4 out of 29 drawers contain specimens that are closer to 6.0 cm)

**Comment by chelseagraham** [comment]
Bi-weekly meeting: 

Group seemed pleased with adopting the 3.6 cm x 2.4 cm FOV for majority of small beetles and the 5.4 cm x 3.6 cm FOV for Pyralids 

Thomas sent the names of some large Danish moths as well as the largest and smallest butterflies at NHMA
Death's head hawkmoth (Acherontia atropos) Dødningehoved SNM:943 DK 70 #40-42 (8-12 cm)
Blue underwing (Catocala fraxini) Blåt ordensbånd SNM:983 DK 168 #178 (7.5-9.5 cm)
Mourning cloak (Nymphalis antiopa) Sørgekåbe SNM:923 DK 94 #142 (6-10 cm)
dwarf leaf-miner enteucha acetosae (Nepticulidae) SNM:887 DK 3 #1 (3-4 mm)

All of these can be accomodated in the FOVs discussed in our meeting

**Comment by PipBrewer** [comment]
NHMA will use 3 fields of view for Lepidoptera: the two also used for pyralids and small beetles and a larger one
