### ISSUE TITLE
Determine if 350 ppi TIFFs of 'Test' images on N:/ are test images and can be deleted

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#65]
I noticed that TIFF images in the following folder 
N:/SCI-SNM-DigitalCollections/DaSSCo/MASTER_IMAGE_STORE/Temporary storage pinned insects/1_WORKPIOF0001/2023-10-16
are 350 ppi
I don't see anyone on the stats sheet for that day. 

Please determine if these 350 ppi images are just images made to test the workflow (do app records and 600 ppi TIFFs exist for these specimens?). If so, determine if they can be deleted? If yes, please delete them? If not, please take note of the specimens that need to be re-imaged (and their locations in the collection). Also determine if they need to be endtered into the app.

**Comment by JesperMJensen** [comment]
Data is exported together with data from 2023-10-18 in:
"N:\SCI-SNM-DigitalCollections\DaSSCo\DigiApp\Data\Archive copies of original preprocessed export files\NHMD_PinnedInsects_20231018_15_46_RL.csv"
It is uploaded in Specify.
Image quality still TBD.

**Comment by JesperMJensen** [comment]
After talking to Thomas:
Data is exported and in Specify.
Images have run through IngestionClient in great quality (~1800 dpi) and are located in:
N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\Main_image_store\WORKPIOF0001\2023-10-30
Jpegs and leftover tifs have been deleted from Temporary storage.
