### ISSUE TITLE
Catch-up Meeting 22 February

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#71]
Topics of Conversation:

- Transcription

**Comment by RebekkaML** [comment]
Here are the notes taken from the meeting: 
[DaSSCo PI Digitization meeting 22-02-2024.pdf](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/14416556/DaSSCo.PI.Digitization.meeting.22-02-2024.pdf)
[DaSSCo PI Digitization meeting 22-02-2024.docx](https://github.com/NHMDenmark/Pinned-Insects-workstation/files/14416557/DaSSCo.PI.Digitization.meeting.22-02-2024.docx)

I also uploaded them to the N-Drive, they are here: N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\DaSSCo Pinned Insects Catch-Up meeting 22.02.2024

**Comment by chelseagraham** [comment]
@Astrid please give an update when the user stories document has been updated with information from this meeting

**Comment by AstridBVW** [comment]
The user stories spreadsheet has now been updated with information from the meeting. It is available on the N-drive.
[Transcription User Stories.xlsx](https://github.com/user-attachments/files/15815753/Transcription.User.Stories.xlsx)
