### ISSUE TITLE
Catch-up Meeting 20 June

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#76]
How to address problems encountered digitizing Dung Beetles https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/68

COUNTS
Previously we discussed potentially adopting entry of specimen counts into the app instead of imaging each specimen for those which share label information. Overall, this practice can be a bit precarious and cannot be adopted across the board as in many cases, specimens are obscured by stacks of cards on the pin and cannot be moved. 

How to mark digitzed specimens in a dynamic and expanding collection https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/60

**Comment by PipBrewer** [comment]
Please add to agenda:

1. Shall we mark determinations from front of drawer as "shelved as" or "stored as" name, so we can separate it from names on labels (which will be added at a later digitisation stage)? It is a check box in the specimen record. NHMD botany, AU and NHMA have all opted to have this. See: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/73 and file:///C:/Users/btw897/Downloads/PinnedInsectCatchup20240320.1.pdf

2. We will send around a monthly report of all taxon names that were entered into the app that were not already present in the taxon spine provided by collection managers. Hopefully this shouldn't happen, but if it does, who is the person responsible for checking these names and correcting them in Specify? We will send the report to that person. We would potentially also send any additional records that need someone to look at them to that person (e.g., if we have a query).
