### ISSUE TITLE
Create two functional stages for Macromoths

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#78]
As a first priority, please create stages for imaging Macromoth based on https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/48 for immediate use

**Comment by Gomismis** [comment]
I have sent .stl files for printing in DIKU (both dung beetles and macro moths), but the printers are really busy at the moment so the prints are ready yet. I have emailed Morten for a status update.

**Comment by Gomismis** [comment]
Stages are printed and in use. Technical drawings can be found  in issue #57
