### ISSUE TITLE
Create second stage for Dung Beetles

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#79]
If https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/78 cannot be done immediately (delays due to wait time with 3D prints, etc) Please create a second Dung Beetle stage for immediate use.

**Comment by Gomismis** [comment]
Check #78 for update on this issue.

**Comment by Gomismis** [comment]
Stages are printed and in use. technical drawings can be found  in issue #57
