### ISSUE TITLE
Create Calibration Protocol for Simplified Pinned Insect Workstations

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#83]
After agreement with Kim that calibration images should be taken after changing the field of view on a simplified workstation, create a protocol for digitizers to generate images for assessment

**Comment by chelseagraham** [comment]
The protocol has been created and is accessible here: N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Pinned_insects/Calibration/CALIBRATION PROTOCOL_Ent.docx

Digitizers are asked to make an update to this ticket and tag @chelseagraham here when there are images to assess

**Comment by nms419** [comment]
@chelseagraham WORKPIOF0001 has been changed from Pyralidae to Macromoth and the calibration images are in the folder. 

I noticed that the protocol has the same naming convention for both images, which does not work. I've just added "checkers" and "white" to differentiate, but we probably need to update the protocol.

**Comment by JesperMJensen** [comment]
@chelseagraham WORKPIOF0001 has been changed back from Macromoth to Pyralidae. Calibration images are in the folder, following the naming convention Sara mentioned above

**Comment by RebekkaML** [comment]
@chelseagraham today I changed the FOV at PIOF01 from Pyralidae to Macromoths and then back again, I took calibration images each time :)

**Comment by RebekkaML** [comment]
@chelseagraham I changed the FOV at PIOF01 from Pyralidae to Macromoths and then back again today, I took calibration images and saved them in the N-Drive folder.

**Comment by RebekkaML** [comment]
@chelseagraham I changed the FOV at PIOF01 from Pyralidae to Macromoths and will change it back again later today. I took calibration images and saved them in the N-Drive folder.

**Comment by annejodobel** [comment]
@chelseagraham I changed the FOV to Macromoths and back to Pyralidae again today.
The calibration images are on the n drive!
