### ISSUE TITLE
Q4 2024: Requests for updates to Pinned Insects Workflow Guides

### ISSUE THREAD

**Issue by nms419** [NHMDenmark/Pinned-Insects-workstation#86]
Updates needed July - September 2024. 

**Pinned Insects Workflow Guide**:
- [x] Add index and linkable headlines
- [x] Edit name to follow version convention
- [x] Added step to check number of digitized specimens to number of images
- [x] Added "Registered" pins and "DaSSCo Digitized" labels
- [x] Slight change of layout

**Shooting pinned insects**:
- [x] Choosing Field of View for new family
- [x] Add Calibration Protocol to use after new FOV has been chosen
- [x] Turning the LCD monitor off
- [x] Turning the mechanichal shutter off
- [x] Edit name to follow version convention
- [x] Add date and time set up for camera to intial set up
- [x] Added a section on how to set daylights savings to Initial Camera Set Up
- [x] Flowchart over setup process added

**Pinned Insects - Barcode printing**:

**Comment by chelseagraham** [comment]
Please print up copies and include at all workstations once revisions have been made and accepted.

**Comment by nms419** [comment]
Document title of the guides have followed "x edit yyyymmdd"-format to differentiate between them. 

This has been changed to "v.1.2.3"-format where 1 signifies major changes, 2 substantial changes and 3 minor changes (starting at v.1.0.0).

Quaterly updates fall under number 2. 

Old versions in the Archive have had their version number added in paranthesis and current guides in the Master folder have had their title changed to version format with a 1 at the end to signify a title change.   

I have made it so that the new version-format follows the old edit-format - 1st edit has become v.1.1.0, 2nd edit is 1.2.0 etc. 
The date the edit started can still be found in the documents header. 

Currently we are updating Pinned Insects Workflow Guide v.1.3.0 and Shooting Pinned Insects v.1.6.0, which can be found in the "Editing in process" folder.

**Comment by chelseagraham** [comment]
@nms419 Please add your wonderful cheat sheet from https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/91 :D

**Comment by PipBrewer** [comment]
Check that the guide is Institution agnostic and more general, with any specific things that are local - taken out and referenced as appendices

**Comment by PipBrewer** [comment]
All of these requests were agreed at the digitiser meeting on 17/09/2024 and should be implemented by end of December 2024.

No more requests for this ticket. The next available ticket for requesting new features/refinements etc is: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/112

If there is any point in this ticket that requires extensive discussion or is particularly complicated, please feel free to make a separate Github ticket for it and reference that ticket number in this one.

**Comment by chelseagraham** [comment]
As we agreed at the Digitizer Meeting yesterday, @nms419 Please release the newest version that you have worked on once all items are addressed except making the guide more generic. 
A further version can then be released that is more generic.

**Comment by nms419** [comment]
The guides have been updated and moved to the Masters folder. Old versions moved to the Archive folder. New versions will be printed and placed by the workstations. 

Please note that the Calibration Protocol added to Shooting Pinned Insects Guide stills needs final approval.

**Comment by chelseagraham** [comment]
I've made answers to the notes in the Calibration Protocol section of the Shooting Pinned Insect Guide here N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/GUIDES/2 Masters/Pinned Insects Guides/Shooting Pinned Insects v.1.6.0.docx 

It looks good and I really appreciate that you made it simpler by creating the kit, @nms419 :)

I just added something to make the kit more specific to NHMD, but feel free to change this as you see it makes the most sense.
