### ISSUE TITLE
Catch-Up Meeting 26 September

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#89]
Chelsea is traveling, so Pip and Rebekka have bene made co-hosts for this meeting via zoom

**Comment by PipBrewer** [comment]
Collection managers and Laura there only. No curators.

PB mentioned:
Successful application for grant to Augustinus
Status of transcription work
Rebekka taking over on operations side
Chelsea and Matilde in London looking at ALICE set up
Expectation is looking at final options for v1 of ALICE on 15th October and should hear something around this time
Data issues (e.g., from DigiApp) to go to Allison
Send this quarter's stats to PB 

Anders asked about how things will be managed at end of funding
PB emphasised that DaSSCo doesn't end at end of this funding, and looking for additonal grants

**Comment by PipBrewer** [comment]
Nothing outstanding from meeting to follow up on.
