### ISSUE TITLE
Decide on whether to include a colour target (ideally yes)

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#9]

**Comment by chelseagraham** [comment]
COLOR CHECKER
**INCLUDING**

Example of insect imaged with scale and color chart:
![image](https://user-images.githubusercontent.com/108529653/222094949-31b0f423-9a49-4043-91bd-0c51828c13c5.png)

_PROS_
Scale can be adjusted to maintain precise level with plane of insect
_CONS_
Scale can be bumped
Scale can become warped, dirtied or damaged
Timely process to adjust or replace
Expensive to replace

**SUPER IMPOSING**

The color checker can be imaged at the beginning of each session and used for white balance / color profiling. Then a digital version of the color checker with correct CIELAB values can be included in a ribbon which is scripted to be superimposed at the bottom of each image.

Example of (not to scale) MOCK-UP super imposed ribbon with institutional information, color chart and scale:
![image](https://user-images.githubusercontent.com/108529653/222095022-d3415fb6-acbe-4973-88fb-bcdb3686695e.png)

_PROS_
Clean and organized appearance
Time saving
_CONS_

**Comment by PipBrewer** [comment]
Let's test for changes during an imaging session

**Comment by chelseagraham** [comment]
I will test including the scale in a series of images over the course of a few hours with the set-up we have now (which may be impacted by ambient light in room 411). When we know the desired location of the Rapberry Pi cameras, we could assess if we might be able to include some kind of manner of blocking light or controlling the influence of external factors.

I have previously tested the performance of the Godox lamps and found that after an initial warm up they performed consistently over the course of 5 hours.

**Comment by chelseagraham** [comment]
Took five images (one image per hour from 10:48 - 14:48) with consistent lighting from Godox lamps and consistent camera parameters. Sampled the L*a*b* and RGB values for a patch on the color checker. Found a tolerance level of up to 3 for L*a*b* and 5 for RGB was necessary due to differences within a patch in an individual image. Found given this tolerance level, the values for the patch between images were within the tolerance level.

Images are on the server at
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Pinned Insects Working Data/ColorCheckerConsistency

**Comment by chelseagraham** [comment]
CONSIDERATIONS

Including a color scale may, at times, necessitate using a larger field of view (FOV). An example of this can be seen with images of this red beetle which measures approximately XX cm

Imaged with a 14.4 cm x 9.6 cm FOV
![Image](https://user-images.githubusercontent.com/108529653/225076905-7db4421c-601a-4be8-ac07-6b39924db639.JPG)


Imaged with a 5.4 cm x 3.6 cm FOV
![Image](https://user-images.githubusercontent.com/108529653/225076737-09278f06-ea04-43a5-8893-88cedb81699d.JPG)


Imaged with a 3.6 cm x 2.4 cm FOV excluding the color target and scale
![Image](https://user-images.githubusercontent.com/108529653/225075157-ab5e7a34-f1c4-4e2f-b1e3-1edb4d43ef7e.jpg)

**Comment by chelseagraham** [comment]
Bi-weekly meeting:

Consensus was that it would be great to include color information for specimens as this is not universally included. 

Given the ability to capture insects during a session under consistent conditions, the group thought the virtual color card was favorable.

**Comment by chelseagraham** [comment]
((add backlog task to make protocol for how we will do this))))
