### ISSUE TITLE
Create a Simplified Pinned Insects Imaging Cheat Sheet and include in Shooting Pinned Insects guide for quick reference

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#91]

**Comment by nms419** [comment]
I've mocked up a flow chart of the Pinned Insects Imaging Workflow, this was the best way I could think of to condense the workflow down to one page. It covers all the major points to set up an imaging session and could work like a check list once you are familiar with the workflow. 

[SPI Cheat Sheet.pdf](https://github.com/user-attachments/files/16349204/SPI.Cheat.Sheet.pdf)

If you're learning the workflow, you would still need to read the guide to get all the finer points. 

Let me know if I should continue down this route or if you had anything else in mind :)

**Comment by chelseagraham** [comment]
Great, Sara! I think that this is a very helpful way of providing an overview and conveying the steps in a visually different manner that may help people who prefer this to blocks of texts (as the imaging guides naturally usually are).
