### ISSUE TITLE
Q4 2024: Requests for refinements and new features for WORKPIOF (all)

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Pinned-Insects-workstation#99]
Please add requests for updates, refinements and new features for the three labels off pinned insect workstations into this ticket.

These will be addressed and prioritised on a quarterly basis.

Next review will be on 17th September 2024.

**Comment by PipBrewer** [comment]
Regarding _Would it not be better to have the labels nearer the digitiser on the digitisation tray? At the moment, the digitiser removes the labels, puts the specimen in the digitisation tray and they takes the labels and works over the top of the specimen and places the label (adding risk and a second or two in time, to the workflow). If it was the other way around, we would take labels off, put specimen on tray and then place labels nearest to digitiser. In reverse, the specimen comes off first and only needs to go over the labels (which is the safer option). The labels are also closer to the digitiser and as there are more of them, there is overall less reaching._

This was discussed in the Digitiser meeting on 17/09/2024. 

SS does not think it is a particular issue at the moment at the speed we are working at; however, if we increase speed the risk increases. PB also wonders whether the time and strain of reaching might become more noticeable.

SS and CG mentioned that it would not be good to keep having to reach up over the slightly raised part of the stage to put the specimen in. 

PB, SS and CG discussed alternatives, including putting labels at one side of the stage, instead of at the top (e.g., either putting stage in upside down or further down the line creating a slightly different stage). CG said that when she was scoping out requirements there was discussion that occassionally some labels (e.g., NHMA) could take up a lot of room. However, it has been noted that majority (all?) so far have not used up that much room in the tray (the larger one). The smaller tray, however, could end up with there not being enough room for labels if we moved that part to the side of the stage. 

No consensus was reached. 

@RebekkaML Drawing this to your attention, but after you have read through and if you are unable to come up with a better solution, please do feel free to close.

**Comment by PipBrewer** [comment]
Check that the guide is Institution agnostic

**Comment by PipBrewer** [comment]
These requests are all agreed and should be implemented by end of December 2024

**Comment by PipBrewer** [comment]
Regarding _Can the digiapp laptop not be on a laptop arm and can be moved closer to and further from the digitiser as needed, or is this not necessary?_

It was agreed that there is a bit of reaching and SS said it would be ideal if either there could be one workstation (rather than workstation and laptop) or the laptop could be positioned on the right side and pulled over (but ensuring there is no risk to specimens).

We talked a bit about whether it would be possible to have DigiApp on workstation computer, but we need to hear back about experiments with shutter release button at NHMA. One thought is that if activate shutter release, the DigiApp window would need to be activated again to scan the next barcode. This is not really efficient. 

@RebekkaML Drawing to your attention. The laptop on a laptop arm is something we could consider, but not urgent or essential at this stage. We also need feedback from NHMA on shutter release. 

UPDATE (from Chelsea):
Charlotte in Aarhus has reported that they have gotten the shutter release to work, but she prefers to use the mouse.

**Comment by PipBrewer** [comment]
In the meeting, CG mentioned something that is urgent (as it involves H&S and digitiser comfort) and that is buying a smaller table on wheels that can be raised (for the specimen tray etc), should the digitiser want to work standing up (the main digitisation table can be raised, but the other one currently can't preventing digitisers being able to work standing up).

We need to scope out the size and height required for this smaller table. 

This table should be bought as part of 2024 Q4 work, with @RebekkaML as lead.

UPDATE (from Chelsea):
In our 31 October Pinned Insect Digitization Catch-up Meeting, we discussed the possibility of a non-electric, hand pump raising table on wheels. Anders mentioned that Thomas Pape once had a table of this kind that he found very sensitive. It would swiftly raise up at the slightest touch, which was a little dangerous for the specimens. So, if we want to go that route, maybe chat about it more with Anders and Thomas to learn about his experience and make sure we don't get one that will do that! 

Also, the Collections Managers expressed their preference for the fixed height table that is currently at WORKPIOF0001 due to its size since they work as a trio, using two stages, etc.

**Comment by PipBrewer** [comment]
No more requests for this ticket. The next available ticket for requesting new features/refinements etc is: https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/111

Please create separate tickets for all refinements/adjustments/features agreed here and link tickets into this one for reference. Once done, please close this ticket.

**Comment by RebekkaML** [comment]
I created a separate issue for getting smaller, height adjustable tables for the PIOF workstations:
https://github.com/NHMDenmark/Pinned-Insects-workstation/issues/135
